spring:
  security:
    oauth2:
      client:
        registration:
          #github:
            #client-id: Ov23lih2Ds1Kqz1tEXOr
            #client-secret: 5c017cc8004513e2014681239496a59a33e498dc
          google:
            client-id: 777017378711-66s4jmdlp0miqt9v0g29enacj22m3mga.apps.googleusercontent.com
            client-secret: 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
            
logging:
  level:
    org:
      springframework:
        security: TRACE
